apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 3
  template:
    metadata:
      name: httpd-server
      labels:
        tier: frontend
    spec:
      containers:
        - name: httpd-image
          image: httpd:2.4-alpine