apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - image: kodekloud/event-simulator
    name: test-container
    volumeMounts:
    - mountPath: /log
      name: task-pv-claim
  volumes:
  - name: task-pv-claim
    persistentVolumeClaim:
      claimName: claim-log-1